Added Pull request for development branch
vinaybajjuri58/learn-finance-backend pull request #1
Opened 2021-05-05 08:52 UTC by vinaybajjuri58

2021-05-23 10:23 UTC, Aravindan07 requested changes
Great Work Vinay your code looks clean and readable.

2021-05-23 10:23 UTC, Aravindan07 commented on index.js
> +initialiseDBConnection();
It is better to initialize the DB connection before every routes i.e., after line 14.

2021-05-23 10:23 UTC, Aravindan07 commented on db/db.connect.js
> +const dbUrl = process.env.DB_URL;
Initializing an unnecessary variable here you can directly pass the DB_URL in the arguments.

2021-05-23 10:23 UTC, Aravindan07 commented on models/User.model.js
> +};
These lines can be reduced into a single line like ``` module.exports = mongoose.model("User",UserSchema); ```

2021-05-23 10:23 UTC, Aravindan07 commented on controllers/playlist.controller.js
> +      .select("__v");
If you want to remove __v from data then add a - sign before that e.g., `.select("-__v")`

2021-05-23 10:23 UTC, Aravindan07 commented on controllers/video.controller.js
> +    res.status(400).json({
This is a 500 error I hope. If it is so please change it.

2021-05-23 10:23 UTC, Aravindan07 commented on controllers/category.controller.js
> +    res.status(400).json({
Here also it's 500 I think. if not then it is fine.

2021-05-23 10:23 UTC, Aravindan07 commented on controllers/category.controller.js
> +  let savedCategory;
Declare it as const you are not changing its value here, right? Then change from let to const

2021-05-23 16:11 UTC, Jaynil1611 requested changes
Great work @vinaybajjuri58 
I have added few suggestions:

2021-05-23 16:11 UTC, Jaynil1611 commented on controllers/category.controller.js
> +    res.status(204).json({
Here the status should be 201 for `post` update operation
```suggestion
    res.status(201).json({
```

2021-05-23 16:11 UTC, Jaynil1611 commented on controllers/category.controller.js
> +const addACategory = async (req, res) => {
Naming of this function could be better like `postCategory` or only `addCategory`
Similarly, everywhere you have used `A` for singular operation, you can rename all such functions

2021-05-23 16:11 UTC, Jaynil1611 commented on controllers/category.controller.js
> +};
Leave a line after each function completion

2021-05-23 16:11 UTC, Jaynil1611 commented on controllers/category.controller.js
> +    const sess = await mongoose.startSession();
Use meaningful variable naming `sess` to `session`

2021-05-23 16:11 UTC, Jaynil1611 commented on controllers/paramHandlers.js
> +    const category = await Category.findById(categoryId).populate("videos");
Here you should have another `try catch` block if the category is not found, then you also should return `res.status(400) ` with `Not found` message

2021-05-23 16:11 UTC, Jaynil1611 commented on controllers/paramHandlers.js
> +    if (playlistData === null) {
This comparison can be simplified by
```suggestion
    if (playlistData) {
```

2021-05-23 16:11 UTC, Jaynil1611 commented on controllers/playlist.controller.js
> +  const videoId = req.body.video;
This should be `req.body.videoId`

2021-05-24 13:14 UTC, Jaynil1611 approved these changes
I am approving the changes

2021-05-24 14:08 UTC, Aravindan07 approved these changes

2021-05-24 14:08 UTC, Aravindan07 commented
You have incorporated all the changes which I asked great work!

2022-12-04 12:38 UTC, merged